### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#104]
We should add some text about how to read markdown. At the very least we should put a small disclaimer saying that lines of code are in ‘’’cryptol code blocks. And everything in ‘’'cryptol code blocks is read into the interpreter when you load the file/module.

**Comment by weaversa** [comment]
What if we changed ‘’’shell to ‘’’interpreter?

**Comment by WeeknightMVP** [comment]
It would be prudent to migrate away from `shell` in order to distinguish Cryptol interpreter sessions from shell scripts, which is really what `shell` and related info strings denote.  `interpreter` would suffice for our purposes for now, but is too broad considering [Linguist-registered info strings](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) and GitHub rendering, because `languages.yml` also specifies a field with `interpreters` for various languages, because various languages have interpreters...

While we await whether Literate Cryptol will refine its parsing to ignore `cryptolicious` or similar info strings starting with `cryptol` for module code, for now we should establish a close variant of whatever space-delimited info strings we wish to use in the long term.  I'll suggest `Xcryptol`, followed by further qualifiers based on the parameters @auricratio [listed](https://github.com/GaloisInc/cryptol/issues/857#issuecomment-668740243), e.g. `Xcryptol session ci-nightly` to denote an interactive session from which to generate nightly CI tests, `Xcryptol session ci-continuous` for per-commit tests, etc.  The leading `X` is a little gross, but distinct, compatible with the present toolchain, still human-readable, and easily relabeled to the intended markup if the toolchain starts supporting it, and this still leaves a Cryptol Markdown renderer with plenty of room to denote specific labels as `hidden`, `private`, `test`, etc.
