### ISSUE TITLE
Clarify cryptol code blocks vs. Xcryptol session blocks

### ISSUE THREAD

**Issue by Reformated** [weaversa/cryptol-course#127]
A number of labs contain this verbiage:

> 
> You do not need to enter the above into the interpreter; the previous
> `:m ...` command loaded this literate Cryptol file automatically.
> In general, you should run Xcryptol session commands in the
> interpreter and leave cryptol code alone to be parsed by `:m ...`.
> 

I suggest adding a clarification for students reading the Preview versions of these modules that cryptol code blocks and Xcryptol session blocks are indistinguishable in the Preview versions of the modules, except possibly by the cryptol prompts shown in the latter.

**Comment by WeeknightMVP** [comment]
This was my mistake, being an experienced Cryptol user that works mostly with the raw Markdown.  It would be nice if Github could highlight code fences based on their info strings, but Cryptol would need a few hundred more repos using it to be taken seriously.  However, this does not stop us from using or developing another highlighter.

**Comment by weaversa** [comment]
We’ve considered making a PR for Cryptol fence markdown pretty printing on GitHub. That’s as far as we’ve gotten :-)

Of course, we’re happy to accept a PR here. Otherwise, do you think we should update *every* lab with some new verbiage? I’m a little worried that the preamble that’s at the top of every lab is too much. We originally had it just on one of the earlier labs, but student’s would miss it, or forget. I was a bit surprised at the number of students who asked why typing ‘module’ into the interpreter caused an error.

**Comment by Reformated** [comment]
In my opinion, the repetition could be cut down a lot.  Describe it carefully in the first module the students encounter.  Thereafter, just say, "As explained earlier in <link-to-first-lab-where-it-happens>, please perform Cryptol interpreter commands listed here such as loading this module:  <show-loading-module>, whereas items like the following Cryptol command, which begins the module definition, require no action on your part:  <module-command>."  Or maybe something even shorter.
