### ISSUE TITLE
Salsa20 (Lab)

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#17]
Let's create a new lab based off of [our old Salsa20 lab](/weaversa/cryptol-course/tree/disused-lavatory/old/Salsa20/).

**Comment by WeeknightMVP** [comment]
There's plenty of material to work with here, already.  We could pull in the [expanded spec](https://github.com/GaloisInc/cryptol-specs/files/3753521/Salsa20.zip) I wrote for [the `cryptol-specs` issue](https://github.com/GaloisInc/cryptol-specs/issues/17) and write a series of exercises guiding the user's development of a Cryptol spec against [the original paper](https://cr.yp.to/snuffle/spec.pdf), porting existing test vectors for the spec to Cryptol, verifying Cryptol's example implementation using SAW, and verifying the simplest of Bernstein's reference implementations (which requires adjustments because the reference implementation doesn't line up exactly with the original paper).

**Comment by weaversa** [comment]
Let's focus on just Cryptol for this lab specifically, and keep the verification ideas for when (if) we get around to saw. Thanks for sharing your spec with all the test vectors. We should totally add the simpler, final ones.

I imagine this lab as teaching someone to write up one of their first real specs in Cryptol, and as such I'd like to keep it simple (one file, no external imports), yet overly verbose and pedantic (for some we won't be around for them to ask questions).

**Comment by WeeknightMVP** [comment]
@weaversa Shouldn't we `undefine` out `Salsa20Encrypt` in `labs::Salsa20::Salsa20` as an exercise?

**Comment by weaversa** [comment]
Thanks @WeeknightMVP !
