### ISSUE TITLE
Yices is required but not mentioned in installation instructions

### ISSUE THREAD

**Issue by rod-chapman** [weaversa/cryptol-course#170]
I am a newbie, learning Cryptol and SAW.

I am running MacOS, and have installed Cryptol 2.11.0, Z3 4.8.10, and SAW 0.8 OK.

Trying the verification of XXHash in Overview.md, the "make" command fails telling me that "yices" is not available. Should the installation instructions page mention that Yices is needed?

Which version of yices (for MacOS) is currently recommended for use with Cryptol?

**Comment by rod-chapman** [comment]
FWIW - I manually installed Yices 2.6.2 and all seems well now with the XXHash verification. MacOS 11.5 initially objects to all these binaries being run, and they have to be manually approved in the Security & Privacy Control Panel, so I guess it might be worth mentioning that in the Installation instructions too...

**Comment by weaversa** [comment]
Thanks Rod! There has been some bit-rot on this and we welcome any attempt to keep it up to date (or at least working).

I was considering testing out GitPod so that folks didn't have to do any setup of the development environment.

Another alternative is to use Docker. Both `cryptol` and `saw` come with Docker containers that have all of the theorem provers installed.

https://github.com/GaloisInc/saw-script/pkgs/container/saw
https://github.com/GaloisInc/cryptol/pkgs/container/cryptol

On your MacOS computer you could create a shell script, one called `cryptol`:
```
docker pull ghcr.io/galoisinc/cryptol:nightly
docker run --rm -it --read-only --mount type=bind,src=/Users,dst=/Users --workdir=$(pwd) --user=$(id -u):$(id -g) --env CRYPTOLPATH=$(pwd) ghcr.io/galoisinc/cryptol:nightly +RTS -N -RTS --no-call-stacks $*
```

and one called `saw`:
```
docker pull ghcr.io/galoisinc/saw:nightly
docker run --rm -it --mount type=bind,src=/Users,dst=/Users --workdir=$(pwd) --user=$(id -u):$(id -g) --env CRYPTOLPATH=$(pwd) ghcr.io/galoisinc/saw:nightly $*
```

And these should operate seamless from the command-line tools. The only issue I have is that some extra control characters show up when running the tools inside an emacs `*shell*` buffer, but that could just be my fault.

**Comment by emlisa3162** [comment]
Cryptol 2.11 works best with Yices 2.6.2 according to the [Dockerfile](https://github.com/GaloisInc/cryptol/blob/74fe8bebc4b547664eea6b3df9936f0bc8ba4e1b/Dockerfile#L27-L30).

I've been looking at some possible ways to make dealing with the mess of solvers a bit easier, both from the dev and user end. Doubt most new/curious users would default to using the provided docker images unless they're pointed to a curated dev environment like gitpod or they are using a hosted instance of cryptol-remote-api.

Something turn-key that gives you recommended versions of everything you need in one go for whatever platform / cryptol version you're using would be kinda cool (with signed binaries for macos). Bonus if it allows easy manual override of versions or compile options for testing newer releases or bugfixes.
